// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma 7.9.1 no soporta directUrl en PrismaConfig; DATABASE_URL
    // (pooled) es la que usa `migrate` en esta versión.
    url: process.env["DATABASE_URL"],
  },
});
